output "kubeconfig" {
  description = "kubeconfig generated by RKE"
  value       = rke_cluster.foo.kube_config_yaml
}

output "api_server_url" {
  value = rke_cluster.foo.api_server_url
}

output "client_cert" {
  value     = rke_cluster.foo.client_cert
  sensitive = true
}

output "client_key" {
  value     = rke_cluster.foo.client_key
  sensitive = true
}

output "ca_crt" {
  value     = rke_cluster.foo.ca_crt
  sensitive = true
}